version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Keep dependencies for Void up-to-date
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'friday'
    ignore:
      - dependency-name: 'autoprefixer-rails'
      - dependency-name: 'uglifier'
      - dependency-name: 'html-proofer'
      - dependency-name: 'rake'
    # Users to assign pull requests for version and security updates
    assignees:
      - 'Stargator'
    reviewers:
      - 'Stargator'
    commit-message:
      prefix: 'Void '
      include: 'scope'
    versioning-strategy: lockfile-only

